### ISSUE TITLE
Make smarter sentries

### ISSUE THREAD

**Issue by afrey15** [famegames/fire-and-ice#100]
**Context** 
There was what felt like a ridiculous amount of sentries that appeared one or two blocks from a wall and then faced said nearest wall and fired directly into it. Our sentries need to be smarter.

**Idea**
Create a check that measures the distance to the nearest big block on either side of the sentry. Have him face whichever direction gives him the more open view and further shooting distance.

**Comment by afrey15** [comment]
Issue #100. Woohoo

**Comment by Regulator13** [comment]
Barotrauma had like 1000 issues, we're 10% there!
