### ISSUE TITLE
Improve Menu System

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire-and-ice#111]
**Context** 
The menu system is complicated and from formatting, appears to use excessive amounts of string checks which are not fast. I have no idea how to make a button or new menu. There are 5 back buttons.

**Idea**
The new menu system should be sleek and efficient. Using a combination of maps and lists, users will be able to create a button with a single line of code, like a function, that specifies the menu, action, location, size, etc. that the button needs. Menus will also be able to be created in a single line, simple creating a space for a list of buttons to go.

**Comment by afrey15** [comment]
It sounds too good to be true tho.. :/

**Comment by afrey15** [comment]
This important discussion has been moved to the Team page.
