### ISSUE TITLE
Explosions no longer do damage

### ISSUE THREAD

**Issue by afrey15** [famegames/fire-and-ice#120]
**Context** 
Explosions are now particles and particles, by definition, cannot have any logic. Therefore, explosions no longer can be used to cause damage. Fortunately, there is no need for explosions to do damage because we have an object that is at the exact position needed to determine what nearby objects will be damaged.

**Idea**
Add logic to `obj_block` and `obj_corpse` so that right before they explode, they do a collision check using a modified collision box (see functions relating to `collision_rectangle`) in order to cause damage. Be sure to also set the object's damage to 1 before this check. Also be sure to destroy water spawns during this check. See obj_explosion for the necessary code that will need to be transferred.

**Comment by Regulator13** [comment]
In interest of game flexibility, I think it makes sense to keep the `obj_explosion` as opposed to a particle. My reasoning for this is that explosions do damage over time. Right now, they kill everything, but in interest of the future, I think we should keep them dealing damage over time. `obj_explosion is not a common or intensive instance and should not slow the game much, as would be the advantage of using particles
