### ISSUE TITLE
Can we change the name of the 0 depth Instance layer

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire-and-ice#24]
The compatibility script has made a long and terrible name for the instance layer. If we change that name will it automatically change the others or cause a bunch of errors? Is there any other way around this?

**Comment by Regulator13** [comment]
After talking to @Phabbits  I'm going to go ahead and try to change it to just "Instances". It appears the compatibility code only assigns a depth to the old creations, not a layer.

**Comment by afrey15** [comment]
Sweet
