### ISSUE TITLE
Lower level lasers

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire-and-ice#28]
**Context** 
The game has just started and you need to think quick. Oops! You're already half dead because you spawned on a block and laser is burning a hole through you.

**Problem or idea**
Don't let lasers spawn on lower levels, I think this will be necessary even after the laser glitch addition

**Solution or next step**
Make the lower bound for lasers, I would say, at least 6 blocks from the bottom, I think the player should be able to jump at the beginning.

**Comment by afrey15** [comment]
Could not agree more. This feels like an issue I might be able to handle..

**Comment by Regulator13** [comment]
I think you have to change one number, which one which one?
