### ISSUE TITLE
Allow water spawns to be blown up

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire-and-ice#31]
**Context** 
A player can throw an exploding block at stuff and it blows up pretty much anything.

**Problem or idea**
Water spawns should be included in this so they don't leave weird floating things.

**Solution or next step**
Make water spawns be destroyed by exploding blocks

**Comment by Phabbits** [comment]
@Regulator13 Why was this not added when they were created?

**Comment by afrey15** [comment]
Isaiah probably didn't notice it immediately. Rather than question the reasoning though, you could also take on the issue and solve the problem!

**Comment by Regulator13** [comment]
*zing*. Yes that was the issue though @Phabbits, I just didn't think about it
