### ISSUE TITLE
Moving Platforms

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire-and-ice#33]
**Context** 
It has been suggested that some platforms should move, either vertically or horizontally, to make the game more interesting.

**Problem or idea**
The platforms must have open room to move in, how do we make it? What should the platforms do when they collide with frozen blocks?  Players must still be able to jump on them will this be an issue @Phabbits?

**Comment by afrey15** [comment]
This will need further discussion.. We could potentially use the same blocks as the existing platforms for the moving blocks. When repeatedly struck with fire, the block could eventually become excited and start to move, perhaps in the direction on the side which the block was struck. Each "platform block" would move just a few block lengths in the direction of the side it was struck before returning to its original position. Upon contact with another block, the new block might change direction immediately.

**Comment by Regulator13** [comment]
I would also like to be able to use the same blocks. I was thinking they would be moving when the room started so you know which ones are moving platforms, but they don't have to be, they could look different instead. Speeding up and slowly down the blocks would happen individually.

**Comment by Regulator13** [comment]
I have an idea for this after hearing your guy's feedback. The platform could be a separate sprite and object. The sprite would have two sub-images (horizontal platform and vertical platform, maybe featuring arrows to specify which way they go). The platform objects would spawn after the room was created in open spaces and could spawn either moving, not, or randomnly.

I think fireballs and iceballs should make the platforms go further in a direction, since the platforms moving quickly will actually probably make no difference at all.

I'll make these changes and you guys can see what you think
