### ISSUE TITLE
Different Character Stats

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire-and-ice#42]
_This is a discussion thread. It can be closed when actions have been taken, such as the creation of new issues._

**Context** 
_Dust: Fire and Ice_ features a number of stats for characters: health, energy, strength, mass, jump height, and max jump number.

**Problem/idea**
We could vary the stats for the different characters!

**Example(s)**
Not a lot, but maybe give the yeti a little more health and mass and a little less jump height. And give santa more energy but less health.

Let me know what you guys think

**Comment by Phabbits** [comment]
There is potential for this, especially with team play. Each member of the team would be able to have a unique character, and therefore a unique purpose in the team. I see a lot of potential with this being combined with issue #39 with certain players having more strength, and therefore the ability to carry more items, and throw them further.

**Comment by Regulator13** [comment]
There is a consensus on this then, I'll try to tackle it
