### ISSUE TITLE
Change water delay increments

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire-and-ice#45]
**Context** 
The water delay currently starts at 1000 (for single player) with a rate of .1 pixels/step and decreases by 200 steps for each level. When the water delay reaches 0 the rate increases by .05 pixels per step each level after that.

**Problem or idea**
The problem is reasonable to impossible very quickly.

**Solution or next step**
I think we should rework this slightly to make the game go more smoothly from easy to difficult. I'd recommend something like this:

Start at 1000 delay, decrease by 100 delay per level until delay is 300. Then increase the water rate by .02 pixels/step each level after that. 

After trying to set high scores a few times, I found it was very frustrating to have the water level at 0 since if there's not enough low platforms you're just dead. I think addressing this now will prevent us from making the game too easy at early levels just to make it possible at later levels.

**Comment by afrey15** [comment]
I agree. This is a good first tweak for this

**Comment by Regulator13** [comment]
Cool, I'll add it to the ever growing pull request I got going then
