### ISSUE TITLE
Realistic Physics

### ISSUE THREAD

**Issue by afrey15** [famegames/fire-and-ice#56]
**Context** 
I have been thinking about how we might lower the barrier to entry, make the physics more realistic, and remove some of the tricky finger-work required with the controls.

**Problem/idea**
I have several ideas that might help with this:

Remove double jump - Double jumps are a tricky finger-work mechanic. In order to get your full jump capacity, you must time your second jump perfectly. It also means you can jump out and back on stacked platforms. That is unrealistic and I think people would not be shocked if they needed to use another means to get around these.

Limit directional changes in air: Players have noted how it is difficult to land on our small frozen blocks. A workaround for everyone has been to jump beyond the platform and then turn back to make the jump easier to land. This does not look good, but fortunately we don't need to rely on it. Preventing players from doing this would make the physics more realistic. As an alternative, the opposite directional arrow when in air, could slow down your hspeed, providing the same effect while looking nicer.

Shorter distance fire and ice shots: Many of these changes are helping players to focus on a smaller portion of the level and become more engaged with it. Shorter fire and ice throwing will be more realistic. I've also noticed that these shots will go through the large blocks so I guess I'll mention that here. The problem of difficult lasers has been mentioned. The laser gaps should be implemented before this happens. As another option, enemies (or little turrets) with guns that fire when you are nearby might replace the lasers altogether. I think this would be a more engaging obstacle than what we have now.

Level Adjustments: To support all of this for the time being, we'll need to spawn more platforms on the map and change the water delays. These should be easy changes. But I think as we add more items and other powers, we'll be able to increase the difficulty again. Actually part of my reasoning is based on this. With the addition of items, soon players will be flying through levels. Making these changes will help make levels difficult again. With how far players can jump and how they can wrap around platforms, there really aren't many block arrangements on the level that are meaningful either. With these changes, players will notice and appreciate the uniqueness of levels more because various block arrangements will represent unique obstacles

Change jump key - This is related to the tricky finger-work issue. Because of the muscle layout in the hand and brain associations, it is not ideal to have the A and the D key for movement and space bar for jump. The W key would make a better jump key. Preferably, we also move all of this over to the directional arrows on the keyboard as they are made for such purposes.

What are you guys' thoughts? Can we proceed with these important changes?

**Comment by Regulator13** [comment]
Now that these have been presented professionally, I can say that I agree with most of them. @afrey15's main point, the game should be focused on the smaller scale, the struggle of getting from block to block.

__Remove double jumps:__ This is worth a shot, although I'm not opposed to double jumps either and I think the single jump + slow down will prove to be basically the same thing. Instead of flying past a block and coming back you'll have to carefully time your slow down to land you exactly on the block, no second chances. However, I think this will increase the usage of my struggle/climb move no one appreciates so I'm willing to try it.

__Limit directional changes:__ Like I said, I'm willing to try it.

__Shorter distance fire and ice shots:__ This is the one I disagree with most. I understand wanting to "zoom in the game" but being able to burn and freeze things further away is a great way of letting players think a little bigger picture. For example, being able to hit a horizontal platform that's further away to get it to come to you, as opposed to having to use a block right in front of you to get anywhere. I like zooming the game in, but I think this actually removes strategy, forcing the trivial solution of always freezing a nearby block because that's the only thing that ever can be done. Still it's easy to test so we can try it, but I would not get too attached to it.

__Level adjustments:__ Naturally the game will be too hard after this so these make sense.

__Change jump key:__ Mine's already W. Isn't everyone's? Weird.

**Comment by afrey15** [comment]
Another thought on double jumps and no personal offense here Isaiah since I believe you created them. They feel to me pasted on to me from the Super Smash series which is one of the most prolific and only users of the double jump concept and I can't help think how unrelated the games are. I've never felt like the Dust Bots would be capable of such acrobats (granted, I know they weren't Dust Bots when you first invented the game). I could see the concept as like a little rocket boost that they had after a jump, but then I think that that could be an item as well. There is another underlying question that I haven't yet presented: how can we give player's near superpowers and expect them to be excited about these items and other new elements? The trampoline is an example. This could be a great item for players to push around a platform and maybe get some kind of double jump out of. Right now it doesn't feel particularly worthwhile.

On the shooting: I notice that your example is based on a new game element and I don't think that is accidental. In most situations up to this point, it really hasn't made a difference to shoot more than a few block's throws. The platforms are a new and rare exception to that. Short little throws feels more realistic and elegant and it aligns with everything else the player can do, which is typically close to their proximity. If the player is able to consider something far away from their position, I think that should be celebrated (Once again, it is a rare situation where shooting further even presents something truly more strategic. Destroying lasers, for example, is something that is just annoying not to be able to do from a distance. It certainly isn't a strategic victory for the player.) I have an item suggestion for a solution here: a gun item could focus your shots, change the appearance, make them shoot straight and far, and make the entire operation feel far more plausible. As we begin to shape how items are obtained, players will examine the level and consider whether the gun might open up such an opportunity that they would otherwise not have.

I know these are personal opinions. For what it's worth, I would not be suggesting any of them if this were going to be a mobile game. I think that the PC game, however, wants something more strategic to engage players. Right now, the primary game struggle is trying to time the throw of those blocks and land on those tiny things without falling. Both of you suggesting items is the reason that I believe you want more strategy. If we want a dexterity game, I think we should cut short and try to improve the dexterity elements we have, because our system has already strayed from uninhibited fun dexterity. We could definitely benefit from some vision casting here, but I see a lot of the potential. For example, more blocks and platforms will mean we might finally see some heavily populated areas that players might need to destroy blocks in. More blocks also means that enemies on those platforms might be much harder to keep safe distance from. More blocks might also mean multiple truly viable routes to the top of that level and chances for players of the same level to find unique and truly different solutions (the items will also help players feel that their solution is something special). 

I'm going to stop while I'm ahead but I think you get the idea. If someone wants to cast a different vision for the game, I would be happy to hear it. I really like to know when people are thinking ahead and not just considering what seems interesting at the time. Thanks @Regulator13 for calling me out on my lack of arguments. I still haven't done a good job of making the big idea tangible but hopefully it makes some more sense. Feedback on these new ideas is welcome.

**Comment by Regulator13** [comment]
Actually @afrey15, if you spend some time bouncing on a trampoline, you'll find your height increases slightly with each bounce until you reach the `gravityMax` (`vspeed = 10`). But if we're going to cripple our players with one jump I would not be opposed to adding in an extra jump off the trampoline as well. 

I'm fine with decreasing the shooting distance some but I don't really like the gun item. I think the advantage it gives the player is just _too_ small and unexciting. "Yay, I can shoot these fireaballs 2 more blocks... maybe I can find a jetpack around here..." I don't think we should have a million items, I think every item should be unique and fun just like every obstacle should be unique and challenging, or sometimes challenging and sometimes helpful like the water droppers.

As for a vision, I see an exciting platform, race-against-the-clock game. Players making daring leaps over an abyss just to barely grab the edge of a block in the middle and struggle up it. I see quick thinkers rapidly deciding which of the two starting platforms they should climb to have a chance to get to the top. I see that one guy deciding that chucking an exploding block above his head is the _only_ way to finish the level, while the other guy steals the jetpack and leaves everyone else in the dust, only to have it strand him on a distant platform with no energy. I think that would be a fun game. All this to say let's add platforms, but not _too_ many platforms.

Btw, I'm currently testing these ideas out, starting with the single jump over on Regulator13_2

**Comment by afrey15** [comment]
I've heard wild tales about Regulator13_2. I'm sure some of it is exaggerated but it seems like there is a whole different game going on there. On the gun: it would not be the difference of 2 blocks. Imagine more like: I throw 3 blocks length normally, but I fire an accurate straight shot infinite distance with the gun, (at the cost of more energy of course).

**Comment by Regulator13** [comment]
Well now there is. If you check out Regulator13_2 and play as the grinch you can witness the full effects of single jump. Just some details of all that was changed to make it possible

__Changes__
- Jump is slightly higher (9.5 compared to 8.5)
- Moving the opposite direction in air will slow you down by the `drag`
- Adjusted climbing to always put you on the side you climbed
- Adjusted trampolines to give you an extra jump if you are going slow enough when you hit them
- Platforms spawn with 50% more frequency

__Effects__
- You can make move back and forth in air, kind of. Wrap around jumps are no longer possible
- Climbing straight up water droplet paths is pretty much impossible (sad but maybe for the best)
- You can stop neatly in the air over a platform to land on it, but you must be careful not to be moving when you hit the platform or you'll fly off
- Game is about 50% more difficult, but it was too easy before so maybe about right now

**Comment by afrey15** [comment]
Wow, that was fast. I can't wait to check this out!

**Comment by Regulator13** [comment]
I also just added an `acceleration` variable that has little effect on the game, you'll barely notice it, but it does allow you to fall off a ledge onto a single ledge block below if you just tap the over key slowly.

**Comment by afrey15** [comment]
Out of sheer curiosity, how is acceleration different from gravity? Is it like a horizontal gravity?

**Comment by Regulator13** [comment]
Not horizontal gravity but kinda like on the ground drag. Drag makes you move over slowly in the air and acceleration makes you start out a little slower on the ground. The difference is drag also makes you stop slowly in the air, but if you want to turn around on the ground, you can do so immediately, instead of slowing down to a stop and then turning around. Which I think makes sense since people don't have to decelerate.
