### ISSUE TITLE
Patrols murder people way too fast

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire-and-ice#59]
**Context** 
If you let a patrol walk all the way through you and back you're dead.

**Problem or idea**
Patrols need to do less damage

**Solution or next step**
Patrols could turn around when they hit you, so they don't kill you right away, or die when they do so much damage to you. Interested in hearing thoughts on this one.

**Comment by afrey15** [comment]
I could see a few options, but I'll vote some kind of hit timer for now. That is, one big hit and then a second or two to give the guy a chance to pass through you completely before he inflicts any more damage.
