### ISSUE TITLE
Fireball and Ice Balls shoot through inner blocks

### ISSUE THREAD

**Issue by afrey15** [famegames/fire-and-ice#66]
They do not shoot through the outer walls, but they do shoot through the big blocks. They should disappear.

**Comment by Regulator13** [comment]
I don't know about this, it makes sense but it is often helpful to be able to shoot through blocks. Of course, now that the characters can barely get fireballs out of their hands it might not be a big deal

**Comment by afrey15** [comment]
This one particularly comes across more as a bug than a helpful feature
