### ISSUE TITLE
Friction/De-acceleration is too low

### ISSUE THREAD

**Issue by afrey15** [famegames/fire-and-ice#67]
Players cannot fall off of a ledge because they de-accelerate too slowly and they will go flying off. Players should not slide when they are moving. They should stop instantly when you let up on the move key because that is how walking works.

**Comment by Regulator13** [comment]
It's not. Just tap left and right when next to an edge and you can fall off ledges. We could make it so if you hold down on the `down` key then you move slowly to the left and right.

**Comment by afrey15** [comment]
This feels like a solid use for the `down` key. I certainly would not be opposed.
