### ISSUE TITLE
Limit jumping launch to ground surfaces

### ISSUE THREAD

**Issue by afrey15** [famegames/fire-and-ice#87]
**Context** 
We have been making several parts of the game more realistic. As I considered this, I thought that it may be nice if characters must be on a solid surface when they jump, as this is how the sort of things works in the real world.

**Idea**
Add code so that characters must have ground below them in order to start a jump.

**Comment by Regulator13** [comment]
This is realistic but you should also note it makes the game harder. We must make up for the difficulty it causes. Wait... hang-glider object? To the discussion!

**Comment by Regulator13** [comment]
Actually another issue, means we have to change trampolines _again_. I can make them bounce you higher than you fall on them but it will compound and everyone will be coming off those things at `gravity_max`. Just so you know
