### ISSUE TITLE
Climbing Mechanic Alternative

### ISSUE THREAD

**Issue by afrey15** [famegames/fire-and-ice#88]
**Context** 
Isaiah graciously introduced to us a climbing mechanism and I found the idea to be very intriguing. During our most recent group playtest, we found that the climbing can be particularly difficult in network games. The mechanic also employs a feature which has gained the endearing term of "button mashing" by modern gamers. I believe this feature could be modified for a new and better climbing experience.

**Idea**
Create a climbing state in which a player will smoothly, albeit slowly, ascend the side of a block with a single press of the up arrow. Expand the feature to include big blocks in order to compensate for the loss of mid-air jumps.

**Possible Implementation**
Upon contact, players must press the up or down arrow to attach and start moving. The feature might also include the down arrow to allow them to climb both directions. This would be useful upon the possible near-future addition of "vertical platforms." Upon reaching the top or bottom of a block or series of blocks, the player should stop and await command. A second up-arrow press would pull the player to the top of the block. A second down arrow press would drop the player off the bottom of the platform. These features would be especially interesting if we *also* had these be an item and not the default. One team member with the grappling hook or ice pick or whatever we call it could position themselves on the vertical wall platform while teammates jump on their heads. We could also give normal players the ability to attach to the wall and not move (but still pull themselves to the top if they are close enough. I don't know, there are so many options.

**Comment by Regulator13** [comment]
I think all players should be able to climb up blocks at any time, but I don't know about walls and bigBlocks. Inching up a small block is like grabbing onto the ledge and pulling yourself up. Climbing up a bigBlock or wall would require an item I think.

It kinda sounds like you want the player to just freeze on the side of blocks and then be able to move smoothly up and down them. This would be pretty easy to implement, if you think that won't look weird. It's just removing gravity

**Comment by afrey15** [comment]
I can appreciate the difference between the two. It should be something like you can struggle a very short distance though so that you can still also attach near the very top of big blocks and make it up the same way (for the sake of logical consistency). As to the auto-attatch, I thought about that, but with my previous idea, we need another check. Make the player press an arrow while in contact in order to initiate that stickiness. As you like, they can latch onto a block or platform, but the serious climb will be saved for the items.

**Comment by Regulator13** [comment]
This makes sense let me just make sure I have things straight:

- Player will jump into the side of a block/bigBlock/wall
- They then can hit the upper arrow to attach to the wall for a second
- If the player is near the top they can hit the up arrow to move smoothly to the top of the block
- If the player is near the bottom they can hit down to go down??? I'm confused by this.
- Once at the top, they have another second to hit the up arrow to climb or they will fall down

**Comment by Regulator13** [comment]
P.S. it all takes energy

**Comment by afrey15** [comment]
You've thought out some critical extra details. Nice. So yah, make contact, press to attach, the hold will last like a second (per your idea), if they are near the top, up again to pull themselves up, otherwise, they fall. The down movement will only be necessary with the climbing item. i.e. climbing can go up or down.

**Comment by Regulator13** [comment]
I like. I make.

**Comment by afrey15** [comment]
And then just as you're doing it keep in mind that climb item and how it will allow you to stay attach to the wall, move up and down it's length, sop you climbing when you hit the top or bottom, and once again allow you to press up again to pull yourself up or down to just drop off and fall
