### ISSUE TITLE
Laser glitches don't work on networking

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire-and-ice#91]
**Bug**
Laser glitches do not occur during a network game

**Expected Behavior**
Laser glitches should occur

**Steps to Reproduce**
1. Go to master
2. Play the game online
3. Note that lasers do not glitch every 8-12 seconds

**Additional Context**
The laser glitches do not work online because of how the laser object is handled in networking, either the method for handling lasers in networking must be changed or a special exception must be programmed in for networking.

**Comment by afrey15** [comment]
You probably are itching for a networking label too lol?

**Comment by Regulator13** [comment]
I am actually

**Comment by Regulator13** [comment]
see #95 before working on this

**Comment by Regulator13** [comment]
Lasers are being removed.
