### ISSUE TITLE
Climbing item (Sticky boots)

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire-and-ice#93]
**Context** 
With the new climbing, you cling to the wall for a second after you collide with it, however, you can't start climbing unless you are nearly at the top.

**Idea**
This item would allow you to use the fire and ice action keys to go up and down (since you can't shoot while climbing) and still use up to complete a climb and down to drop off. Like the jetpack, it would cost energy whenever you move up or down the wall.

**Comment by afrey15** [comment]
I don't think sticky boots is the best name for this. Good footwear is important for climbing, but if something was going to be sticky, I would want it to be my hands and not my feet. Sticky gloves or climbing gloves might be good (they have futuristic suction gloves like this that let you scale smooth walls). Climbing picks are another option (little ice picks that you can use to climb walls-these are more even more real).

**Comment by Regulator13** [comment]
Yeah I couldn't think of a good name. I didn't think grappling hook was right because this is specifically for walls you can't necessarily get on top of. I think I might go with the climbing picks
