### ISSUE TITLE
Hang Glider

### ISSUE THREAD

**Issue by Regulator13** [famegames/fire-and-ice#94]
**Context** 
Players can no longer jump in mid-air, due to realism complaints. This is good but it makes it difficult to travel much horizontal distance which the old Dust characters could do with ease.

**Idea**
Make a hang glider object. This is not an item and would be carried above the head as the `Grab_object` just like the jetpack. Unlike the jetpack though, it would take no energy. The effect is very simple, if a player is falling the gravity is greatly reduced. This allows a player to glide horizontally from one side to the other if they can get a little height.

**Comment by afrey15** [comment]
This one is particularly brilliant. I like it.

**Comment by Regulator13** [comment]
Why thank you, you should see it in action by tonight
