### ISSUE TITLE
Sentry (replacement idea for the wall-mounted laser)

### ISSUE THREAD

**Issue by afrey15** [famegames/fire-and-ice#95]
**Context** 
Lasers were never quite implemented the way I imagined the idea. In addition, our playtests have provided a lot of useful information about how they could be improved.

**Idea**
Remove and replace lasers with the sentry guard. The sentry is an actual character with an appearance about identical to the enemies that currently walk back and forth on some platforms. However, unlike those enemies, he stands in one place on a platform and faces one direction. He is also armed with a laser gun. The laser gun shoots long laser beams (of a big block's length or so) when characters are near (in order to be near, a character must be in a certain range above or below the sentry and on the side that he is facing).

**Reasoning**
In my opinion, the lasers are not a reasonable obstacle. They are either in the way or, if the glitch is active, or they are easily dismissed. Blocking lasers with blocks was cool but it was also one of those particularly tricky mechanics (about on the level of how difficult it used to be to land on a block). It isn't completely intuitive that lasers can be destroyed, but I think it will be if they are sentry enemies. Also, laser beams from a gun have gaps between them which can be dodged. With the solid lasers, players either blocked them if they could or just took the damage where necessary. I think the chance to dodge the obstacle may make it more exciting. Finally lasers needed special implementation on networking because of their massive CPU use. My hope is that these sentry guards will require so much less processing power that they can once again be controlled and programmed the same as all of our other items and obstacles.

**Comment by Regulator13** [comment]
As much as I hate to agree with @afrey15 this makes a lot of sense. The sentries would be more intuitive and firing lasers would be a nice medium between completely on and completely off lasers. I also like the facing one direction idea. I like the across-map nature of lasers but that they were completely unavoidable most the time was annoying.

I'd be happy to implement this alongside lasers to give people a chance of seeing what they are like before removing lasers
