### ISSUE TITLE
Create "ledge hanging" mechanic

### ISSUE THREAD

**Issue by afrey15** [famegames/fire-and-ice#98]
**Context** 
During our latest playtest, I noticed that climbing and clinging to shear wall faces could be more smooth and realistic.

**Idea**
Give characters the ability to ledge hang instead of cling and climb shear wall faces. Ledge hanging will allow characters to cling only when they are their bodies are, or have fallen, parallel with the side of a platform, giving the thought and appearance that the character is hanging from the side of the ledge.

**Steps**
- Remove wall clinging and climbing for characters without climbing picks.
- Add 'ledge hanging' to allow players to cling infinitely to a ledge
- Allow falling from ledge if down arrow is pressed
- Allow pulling to top in one fluid action if up arrow is pressed
- Create reverse pulling to top by pressing the down arrow on the edge of a platform

**Comment by Regulator13** [comment]
Phew, this is totally different from what I had just implemented. I see that it doesn't really make sense but did you see how much we used climbing? We used it to get everywhere, and we definitely weren't parallel with the edge when we were climbing. I imagine it made it much easier with the glitchy controls. 

I like being able to hang off the ledge indefinitely, but I think that climbing isn't, at the least, bad as it is. Also the reverse pulling thing would not work with the 'inch' mechanic I also just implemented.

These ideas aren't bad but I just spent hours implementing what we had agreed on and now you want to scrap them? I'd be willing to change this stuff later but I'm not treating this as any sort of priority

**Comment by afrey15** [comment]
I don't think its fair to say that I want you to scrap hours of previous work since most of that code would still be necessary. I didn't know climbing down on a ledge would mean getting rid of pressing down to slow movement. I also don't think its accurate to say this is totally different from what you made.

**Comment by Regulator13** [comment]
I just want you to carefully consider what you're asking for before you ask me to make changes, because I told you what I was going to do last time and you said okay. What do you mean by:
>  Ledge hanging will allow characters to cling only when they are their bodies are, or have fallen, parallel with the side of a platform
Pixel perfect parallel? A tolerance of a a few pixels? If the player is 5 pixels from the top then suddenly moves or climbs to be perfectly parallel will that really look that much different from now?

Also these:
> Allow falling from ledge if down arrow is pressed
> Allow pulling to top in one fluid action if up arrow is pressed

are already implemented

**Comment by afrey15** [comment]
It would be zero tolerance. Only at perfect parallel would they stop. If they are higher than that, then they fall until they hit that parallel position where they catch. If they are lower than perfect parallel they just fall. The 'hanging' state should really be different from the 'climbing' state. Once they reach parallel with the ledge during climbing, they are at the top. They can no longer climb any higher (or they shouldn't be able to). At this point, they must pull themselves up. This was a distinction I was trying to get across the first time, but I didn't do a good job of it. Some of this is different too because seeing it has helped understand the idea. The reason I include those two extra steps that you quote in your comment is because they would need to work for the 'hanging' state also. Characters can hang indefinitely.

**Comment by Regulator13** [comment]
Ah, I gotcha now. I think the current hang state could me modified to happen indefinitely and only at perfect parallel. The thing is you have to remember that characters don't travel every pixel when they're falling. They jump their `vspeed` in pixels each step, never touching the places in between. The `gravity_max` is 10 which means a character could jump as many as 10 pixels in a single step, from above a block to halfway down it. Do you have an idea to combat this issue? Perhaps the slide effect I implemented before that makes the character slide slowly down the side of blocks, but this doesn't occur for big blocks.

**Comment by afrey15** [comment]
I was not a huge fan of the slide effect. Could we anticipate this variable fall speed? Players falling at speed 10 would not need to be able to grab a ledge, realistically speaking. But, and maybe you were suggesting this, we could have that check occur at parallel through to 6-7-8 pixels above parallel, and then transport the character to parallel where they stop. I'm not sure how it would look.

**Comment by Regulator13** [comment]
This is what was happening before, I would just reduce the climb tolerance from 24 pixels down to 6

**Comment by Regulator13** [comment]
I could move them to be exactly parallel and wait at parallel instead of waiting at wherever within 6 pixels they landed which is what I was doing before

**Comment by afrey15** [comment]
Yah, they should drop down to parallel. I'm not confident that were on the same page yet.. So at parallel, no upward climbing should be possible. That is the highest you can go.

**Comment by Regulator13** [comment]
Here's what I'm picking up so far:

__Players without picks__
- Run and jump into walls normally, and do not slide down them or stick to them
- If a player lands with 6 pixels (up or down) of parallel they transport so their head is level with the block
- They remain there until they hit up to climb up or down to drop
- Probably climbing itself will be the only thing that takes energy and you can hang indefinitely

__Players with picks__
- Function like before, but if you are within 6 pixels of the ledge teleport to parallel
- The player must then climb or drop

**Comment by afrey15** [comment]
A few clarifications:

Players without picks

- cannot climb
- can pull themselves up when hanging from a block (a single tap of the up arrow initiates the sequence to pull themselves to the top)

Players with picks

- still enter hanging state when they are parallel with the top
- use the same up press to pull themselves up, as opposed to the mouse clicks they use to climb

**Comment by Regulator13** [comment]
I read ya

**Comment by afrey15** [comment]
Hanging state will be accompanied by animations that make it look less awkward.
